CREATE TABLE domain
(
  ID              UUID,
  NAME            VARCHAR(255) NOT NULL,
  ORGANISATION_ID UUID,
  LAST_UPDATED    TIMESTAMP,
  CREATED         TIMESTAMP NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (ORGANISATION_ID) REFERENCES organisation (id)
);